import { FieldValue, Timestamp, type DocumentData, type QueryDocumentSnapshot } from "firebase-admin/firestore";
import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";
import { getAdminDb } from "./admin";
import type { WeeklyPlanDoc, WeeklyPlanFolderDoc, WeeklyPlanTagDoc } from "@/lib/types";

/**
 * Server-only Firestore CRUD for `weeklyPlans` — the manually-created lesson
 * plans that replace scripts/generate-week.ts's folder-scanning. Each plan
 * still provisions a real local `.excalidraw` file (same as before), it's
 * just created once by the "+ New Lesson" modal instead of generated by the
 * script — see createWeeklyPlan below. See lib/types.ts's WeeklyPlanDoc.
 */

const WEEKLY_PLANS = "weeklyPlans";

function tsToIso(value: unknown): string | undefined {
  if (value instanceof Timestamp) return value.toDate().toISOString();
  if (typeof value === "string") return value;
  return undefined;
}

function planFromDoc(doc: QueryDocumentSnapshot<DocumentData>): WeeklyPlanDoc {
  const data = doc.data();
  return {
    id: doc.id,
    groupId: typeof data.groupId === "string" ? data.groupId : "",
    date: typeof data.date === "string" ? data.date : "",
    topic: typeof data.topic === "string" ? data.topic : "",
    excalidrawPath: typeof data.excalidrawPath === "string" ? data.excalidrawPath : "",
    teacherNotes: typeof data.teacherNotes === "string" ? data.teacherNotes : "",
    emojis: Array.isArray(data.emojis) ? data.emojis.filter((e: unknown): e is string => typeof e === "string") : [],
    order: typeof data.order === "number" ? data.order : undefined,
    folderId: typeof data.folderId === "string" ? data.folderId : "",
    tagIds: Array.isArray(data.tagIds) ? data.tagIds.filter((t: unknown): t is string => typeof t === "string") : [],
    createdAt: tsToIso(data.createdAt),
    updatedAt: tsToIso(data.updatedAt),
  };
}

/** Every plan, ordered for the sidebar queue: by `order` when set (drag-reordered), falling back to date for anything not yet touched. */
export async function listWeeklyPlans(): Promise<WeeklyPlanDoc[]> {
  const snap = await getAdminDb().collection(WEEKLY_PLANS).get();
  const plans = snap.docs.map((doc) => planFromDoc(doc as QueryDocumentSnapshot<DocumentData>));
  return plans.sort((a, b) => {
    if (a.order !== undefined && b.order !== undefined) return a.order - b.order;
    if (a.order !== undefined) return -1;
    if (b.order !== undefined) return 1;
    return a.date.localeCompare(b.date);
  });
}

/** "money & shopping!" -> "money-shopping" — keeps the on-disk filename filesystem-safe and readable. */
function slugifyTopic(topic: string): string {
  const slug = topic
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "lesson";
}

const LESSONS_ROOT = "lessons";
const BLANK_SCENE = { type: "excalidraw", version: 2, elements: [], appState: {} };

/** Creates a new `weeklyPlans` doc AND a blank `.excalidraw` file on disk at `lessons/{groupId}/{date}-{topic-slug}.excalidraw` — the "+ New Lesson" modal's Save action. `groupId` is expected to already be a valid group doc id (slug), so it also doubles as the on-disk folder name, same convention scripts/generate-week.ts used. */
export async function createWeeklyPlan(data: {
  groupId: string;
  date: string;
  topic: string;
  teacherNotes: string;
  emojis: string[];
  tagIds?: string[];
}): Promise<WeeklyPlanDoc> {
  const fileName = `${data.date}-${slugifyTopic(data.topic)}.excalidraw`;
  const excalidrawPath = path.posix.join(LESSONS_ROOT, data.groupId, fileName);

  const absoluteDir = path.join(process.cwd(), LESSONS_ROOT, data.groupId);
  await mkdir(absoluteDir, { recursive: true });
  await writeFile(path.join(absoluteDir, fileName), JSON.stringify(BLANK_SCENE), "utf-8");

  const ref = getAdminDb().collection(WEEKLY_PLANS).doc();
  await ref.set({
    groupId: data.groupId,
    date: data.date,
    topic: data.topic,
    excalidrawPath,
    teacherNotes: data.teacherNotes,
    emojis: data.emojis,
    folderId: "",
    tagIds: data.tagIds ?? [],
    createdAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
  });
  const doc = await ref.get();
  return planFromDoc(doc as QueryDocumentSnapshot<DocumentData>);
}

/** Patches a plan's `order`, `teacherNotes`, `folderId`, and/or `tagIds` — the sidebar's drag-reorder/drag-to-folder, the Teacher Notes panel's save, and the tag picker, respectively. Never touches groupId/date/topic/excalidrawPath (a plan's identity and its file on disk are fixed at creation). */
export async function updateWeeklyPlan(
  id: string,
  updates: { order?: number; teacherNotes?: string; folderId?: string; tagIds?: string[] }
): Promise<WeeklyPlanDoc | null> {
  const ref = getAdminDb().collection(WEEKLY_PLANS).doc(id);
  const existing = await ref.get();
  if (!existing.exists) return null;
  await ref.update({ ...updates, updatedAt: FieldValue.serverTimestamp() });
  const doc = await ref.get();
  return planFromDoc(doc as QueryDocumentSnapshot<DocumentData>);
}

export async function getWeeklyPlan(id: string): Promise<WeeklyPlanDoc | null> {
  const doc = await getAdminDb().collection(WEEKLY_PLANS).doc(id).get();
  if (!doc.exists) return null;
  return planFromDoc(doc as QueryDocumentSnapshot<DocumentData>);
}

/** Re-validates a plan's stored excalidrawPath never escapes /lessons, same belt-and-suspenders as lib/teaching.ts's resolveCurrentBoardPath — the plan doc is trusted (we wrote excalidrawPath ourselves in createWeeklyPlan), but this stays cheap insurance against a hand-edited Firestore doc. */
function resolveBoardPath(plan: WeeklyPlanDoc): string {
  const root = path.join(process.cwd(), LESSONS_ROOT);
  const filePath = path.join(process.cwd(), plan.excalidrawPath);
  const resolvedRoot = path.resolve(root) + path.sep;
  if (!path.resolve(filePath).startsWith(resolvedRoot)) throw new Error("Invalid excalidraw path.");
  return filePath;
}

export async function readWeeklyPlanBoard(plan: WeeklyPlanDoc): Promise<unknown> {
  const buffer = await readFile(resolveBoardPath(plan), "utf-8");
  return JSON.parse(buffer);
}

export async function writeWeeklyPlanBoard(plan: WeeklyPlanDoc, scene: unknown): Promise<void> {
  await writeFile(resolveBoardPath(plan), JSON.stringify(scene), "utf-8");
}

// ---------------------------------------------------------------------------
// Weekly plan folders — organizational tree for the sidebar's "Weekly Plans"
// queue (nestable via parentId, colorable via a preset/custom hex, Obsidian
// vault-style). Drag a plan onto a folder to file it there (see
// updateWeeklyPlan's folderId above); drag a folder onto another to nest it.
// ---------------------------------------------------------------------------

const WEEKLY_PLAN_FOLDERS = "weeklyPlanFolders";

function folderFromDoc(doc: QueryDocumentSnapshot<DocumentData>): WeeklyPlanFolderDoc {
  const data = doc.data();
  return {
    id: doc.id,
    name: typeof data.name === "string" ? data.name : "",
    order: typeof data.order === "number" ? data.order : 0,
    parentId: typeof data.parentId === "string" ? data.parentId : null,
    color: typeof data.color === "string" ? data.color : null,
  };
}

export async function listWeeklyPlanFolders(): Promise<WeeklyPlanFolderDoc[]> {
  const snap = await getAdminDb().collection(WEEKLY_PLAN_FOLDERS).orderBy("order").get();
  return snap.docs.map((doc) => folderFromDoc(doc as QueryDocumentSnapshot<DocumentData>));
}

/** Appends a new folder after the current last one — the sidebar's "+ Add Folder" button (and each folder header's "+ subfolder" button, via parentId). */
export async function createWeeklyPlanFolder(name: string, parentId: string | null = null, color: string | null = null): Promise<WeeklyPlanFolderDoc> {
  const existing = await listWeeklyPlanFolders();
  const ref = getAdminDb().collection(WEEKLY_PLAN_FOLDERS).doc();
  const data = { name, order: existing.length, parentId, color };
  await ref.set(data);
  return { id: ref.id, ...data };
}

/** Returns false if the folder doesn't exist, or if moving it into `parentId` would nest it inside itself/a descendant. */
export async function updateWeeklyPlanFolder(
  id: string,
  updates: { name?: string; parentId?: string | null; color?: string | null }
): Promise<boolean> {
  const db = getAdminDb();
  const ref = db.collection(WEEKLY_PLAN_FOLDERS).doc(id);
  const existing = await ref.get();
  if (!existing.exists) return false;

  const patch: Record<string, unknown> = {};
  if (updates.name !== undefined) patch.name = updates.name;
  if (updates.color !== undefined) patch.color = updates.color;

  if (updates.parentId !== undefined) {
    const allFolders = await listWeeklyPlanFolders();
    let cursor = updates.parentId;
    while (cursor) {
      if (cursor === id) return false;
      cursor = allFolders.find((f) => f.id === cursor)?.parentId ?? null;
    }
    patch.parentId = updates.parentId;
  }

  await ref.update(patch);
  return true;
}

/** Recursively deletes a folder and its subfolders. Plans inside are unfiled (folderId ""), never deleted — a lesson plan is real work, not disposable folder metadata. */
export async function deleteWeeklyPlanFolder(id: string): Promise<boolean> {
  const db = getAdminDb();
  const allFolders = await listWeeklyPlanFolders();
  if (!allFolders.some((f) => f.id === id)) return false;

  const toDelete = new Set<string>([id]);
  let grew = true;
  while (grew) {
    grew = false;
    for (const f of allFolders) {
      if (f.parentId && toDelete.has(f.parentId) && !toDelete.has(f.id)) {
        toDelete.add(f.id);
        grew = true;
      }
    }
  }

  const plansSnap = await db.collection(WEEKLY_PLANS).where("folderId", "in", Array.from(toDelete).slice(0, 30)).get();
  const batch = db.batch();
  for (const doc of plansSnap.docs) batch.update(doc.ref, { folderId: "", updatedAt: FieldValue.serverTimestamp() });
  for (const folderId of toDelete) batch.delete(db.collection(WEEKLY_PLAN_FOLDERS).doc(folderId));
  await batch.commit();
  return true;
}

// ---------------------------------------------------------------------------
// Weekly plan tags — reusable, created-first entities (not freeform text).
// Attached to a plan by id via WeeklyPlanDoc.tagIds; the tag picker creates
// one here before it can be selected.
// ---------------------------------------------------------------------------

const WEEKLY_PLAN_TAGS = "weeklyPlanTags";

function tagFromDoc(doc: QueryDocumentSnapshot<DocumentData>): WeeklyPlanTagDoc {
  const data = doc.data();
  return { id: doc.id, name: typeof data.name === "string" ? data.name : "", color: typeof data.color === "string" ? data.color : "" };
}

export async function listWeeklyPlanTags(): Promise<WeeklyPlanTagDoc[]> {
  const snap = await getAdminDb().collection(WEEKLY_PLAN_TAGS).orderBy("name").get();
  return snap.docs.map((doc) => tagFromDoc(doc as QueryDocumentSnapshot<DocumentData>));
}

export async function createWeeklyPlanTag(name: string, color: string): Promise<WeeklyPlanTagDoc> {
  const ref = getAdminDb().collection(WEEKLY_PLAN_TAGS).doc();
  await ref.set({ name, color });
  return { id: ref.id, name, color };
}

export async function updateWeeklyPlanTag(id: string, updates: { name?: string; color?: string }): Promise<boolean> {
  const ref = getAdminDb().collection(WEEKLY_PLAN_TAGS).doc(id);
  const existing = await ref.get();
  if (!existing.exists) return false;
  await ref.update(updates);
  return true;
}

/** Deletes the tag and strips it from every plan that carries it. */
export async function deleteWeeklyPlanTag(id: string): Promise<boolean> {
  const db = getAdminDb();
  const ref = db.collection(WEEKLY_PLAN_TAGS).doc(id);
  const existing = await ref.get();
  if (!existing.exists) return false;

  const plansSnap = await db.collection(WEEKLY_PLANS).where("tagIds", "array-contains", id).get();
  const batch = db.batch();
  for (const doc of plansSnap.docs) {
    const tagIds = (doc.data().tagIds as string[] | undefined) ?? [];
    batch.update(doc.ref, { tagIds: tagIds.filter((t) => t !== id), updatedAt: FieldValue.serverTimestamp() });
  }
  batch.delete(ref);
  await batch.commit();
  return true;
}
